# active spring boot profile
spring:
   profiles:
      active: dev
---
# common spring boot configuration
spring:
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   messages:
      basename: messages/messages_ko
      encoding: UTF-8
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB
   aop:
      auto: true
      proxy-target-class: true
---
# dev profile - spring boot configuration 
spring:
   config:
      activate:
         on-profile: dev
   jwt:
      secret: PeAChHOng
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mehago?characterEncoding=utf8
      username: root
      password: asd003786
---
# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.80.105:3307/mehago?characterEncoding=utf8
      username: mehago
      password: mehago
---
# server
server:
   port: 8080
   servlet:
      encoding:
         charset: UTF-8
         enabled: true

---
#mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

#---
#logging
# logging:
#   config: classpath:logback.xml